### PR TITLE
WIP - Update and rename README.rst to README.md

### PR DESCRIPTION
**Pull request by ryaminal**
#### Convert README from rst to markdown(markup?)
Rename and convert rst to markdown using pandoc

#### Motivation
Support syntax highlighting for the main README.

Currently without syntax highlighting the README is quite challenging to read from the browser

This is a Github issue, I believe.
Apparently Github just stopped syntax-highlighting on rst code-blocks?

#### Tests
This file is used in some tests and is `doctest`ed.

If this change is at all desirable, I will fix all those but figured I'd gauge the interest here before going too crazy.

#### Checklist

Before you create the PR, please make sure you have:

- [X] Picked a concise, informative and complete title
- [X] Clearly explained the motivation behind the PR
- [ ] Linked to any existing issues that your PR will be solving
- [ ] Included tests for any new functionality
- [ ] Checked that all unit tests pass

### CODE REVIEW

**Comment by ddelange** [comment]
it's a new issue: https://github.com/github/markup/issues/1796

**Comment by mpenkov** [comment]
setup.py (and thus PyPI) relies on the readme being in RST format.

https://github.com/piskvorky/smart_open/blob/b3d862106d1d22f891ec4bb1bacc9d092b42fcfe/setup.py#L59

I'd rather not mess with it unless we absolutely have to.

**Comment by ddelange** [comment]
fwiw

setup.py can take `long_description_content_type="text/markdown"`
https://github.com/ddelange/pipgrip/blob/e191348bdcec4305b77e8220dd9b6735999cb91d/setup.py#L62

pyproject.py will even read the readme contents for you, and detect content type based on extension
https://github.com/ddelange/mapply/blob/5ed4003bb2b5184724019df9ed0f132f6ee69dd3/pyproject.toml#L8

both render properly on pypi

**Comment by ryaminal** [comment]
Looks like github fixed the issue upstream. Feel free to close this.

**Pull request closed without merging**
