### PR TITLE
Ignore httpretty 0.12

### PR DESCRIPTION
**Pull request by tmylk**
httpretty 0.12 breaks Python 3 builds. 
https://github.com/gabrielfalcao/HTTPretty/issues/278

### CODE REVIEW

**Comment by tmylk** [comment]
Fails with


=====================================================================
ERROR: test_write (smart_open.tests.test_smart_open.WebHdfsWriteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 3, in wrapper
  File "/home/travis/build/piskvorky/smart_open/smart_open/tests/test_smart_open.py", line 463, in test_write
    smart_open_object.close()
  File "/home/travis/build/piskvorky/smart_open/smart_open/smart_open_lib.py", line 560, in close
    self.upload(buff)
  File "/home/travis/build/piskvorky/smart_open/smart_open/smart_open_lib.py", line 523, in upload
    response = requests.post(uri, data=data, headers={'content-type': 'application/octet-stream'})
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/requests/models.py", line 296, in prepare
    self.prepare_body(data, files, json)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/requests/models.py", line 447, in prepare_body
    body = self._encode_params(data)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/requests/models.py", line 84, in _encode_params
    return to_native_string(data)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/requests/utils.py", line 700, in to_native_string
    out = string.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 0: ordinal not in range(128)
----------------------------------------------------------------------

**Comment by piskvorky** [comment]
We can fix `httpretty` at some working version.

But it looks like this PR still fails, even with the fixed version, at `smart_open.tests.test_smart_open.WebHdfsWriteTest`?

**Comment by tmylk** [comment]
It Fails with the exact error that the version bump from 0.8.8 to 0.8.10 #40 was supposed to fix..

**Comment by piskvorky** [comment]
I don't think so. That error had to do with installing `httpretty`, not running `WebHdfsWriteTest`.

**Comment by nikicc** [comment]
What are future plans for this? Are we waiting for `httpretty` to fix [issue 278](https://github.com/gabrielfalcao/HTTPretty/issues/278) and will then update to `0.8.12`?

**Comment by tmylk** [comment]
Yes, unfortunately we are waiting on httpretty along with other projects downstream of them.

**Comment by tmylk** [comment]
However it's a mocking library and a test time requirement - you can try running smart_open with the next version.

**Pull request merged**
