### PR TITLE
Resolve issue #12 (unable to read gz from S3)

### PR DESCRIPTION
**Pull request by mpenkov**

### CODE REVIEW

**Comment by tmylk** [comment]
Thanks for the PR!

Can we make it an optional dependency until `gzipstream` appears on PyPi? i.e. try/catch around import 

Several people requested for `gzipstream` to be added to PyPi but t is not likely to happen. Git install is ok for us.  https://github.com/Smerity/gzipstream/issues/3

**Comment by piskvorky** [comment]
Does bundling `gzipstream` make sense? Are the licenses compatible?

**Comment by tmylk** [comment]
We can re-license the MIT-licensed `gzipstream` as we see fit.

**Comment by mpenkov** [comment]
@tmylk Gzipstream is optional already. If it's not installed, ImportError is caught and gzipstream-related functionality is disabled.

@piskvorky I wouldn't recommend bundling. If someone improves it e.g. by adding write capability we'd have to re-bundle. It isn't a required component, and is not that hard to install, anyway.

**Comment by piskvorky** [comment]
Thanks for feedback @mpenkov . I'm actually still +1 on bundling, if it's a simple, pure-Python script. 

Potential "rebundling" seems straightforward, the added functionality very neat for us to rely on, and asking users to git-install unnecessarily demanding.

But I'll defer the decision to @tmylk .

Are there any performance implications?

**Comment by tmylk** [comment]
I would like to bundle it as there has been no changes to it for 2 years. We are in better position to add write capability than current maintaners.

**Comment by mpenkov** [comment]
Ok, those are good points. I'll do it later today.

**Comment by mpenkov** [comment]
@tmylk Just to double-check, gzipstream is GNU GPL **not** MIT. If we bundle it, what do we do about their license? Do we have to do anything to our MIT license? Or do the two just coexist side-by-side? I'm not a lawyer, so I thought I'd check :)

**Comment by tmylk** [comment]
Their github is confusing. It says MIT in Readme and GPL in the license file.
If it is GPL then we can't use it.

**Comment by tmylk** [comment]
Let's hope the maintainer gets back quickly to my query in https://github.com/Smerity/gzipstream/issues/7

**Comment by mpenkov** [comment]
Not sure why the Travis CI build failed, it looks like it could be issue #62.

**Comment by mpenkov** [comment]
Included by https://github.com/piskvorky/smart_open/pull/76

**Pull request closed without merging**
