### PR TITLE
Propagate uri to compression_wrapper

### LINKED ISSUE #841: FTP stream decompression - unable to transparently decompress
#### Problem description

Be sure your description clearly answers the following questions:

When attempting to decompress a file stream from an FTP source, I am getting
```
WARNING unable to transparently decompress <_io.BufferedReader name=4> because it seems to lack a string-like .name
```
This then causes errors as it returns the still compressed file blob.

#### Steps/code to reproduce the problem

```python
import smart_open
import logging
logging.basicConfig(
    level='DEBUG'
)

def main():
    streamreader = smart_open.open(uri='ftp://myftp.example//myfile.txt.gz', mode='r', errors='surrogateescape', encoding='utf-8')
    print(streamreader.__next__())

if __name__ == '__main__':
    main()
```

Output:
```
DEBUG:smart_open.smart_open_lib:{'uri': 'ftp://myftp.example//myfile.txt.gz', 'mode': 'r', 'buffering': -1, 'encoding': 'utf-8', 'errors': 'surrogateescape', 'newline': None, 'closefd': True, 'opener': None, 'compression': 'infer_from_extension', 'transport_params': None}
WARNING:smart_open.compression:unable to transparently decompress <_io.BufferedReader name=580> because it seems to lack a string-like .name
DEBUG:smart_open.smart_open_lib:encoding_wrapper: {'fileobj': <_io.BufferedReader name=580>, 'mode': 'r', 'encoding': 'utf-8', 'errors': 'surrogateescape', 'newline': None}
▼���r�8��y�O����ٰ\♦�����Gf�TWugMWTfw�\9(        �X�H5I��        ]���l►�-�i��G��g.&�2y�u@�~▬A|���ok?�A��ُe���9�%-n�bz�R6�n�:+♂V��☼⌂a�Vj��▬�}�▬���}��a������D�������<��t��♂�ؗ"�↨��Oy�`?��J������O�����fu�>�dEqϲ�������
```

I (poorly) tweaked [smart_open_lib.py#L225](https://github.com/piskvorky/smart_open/blob/develop/smart_open/smart_open_lib.py#L225) to include the `filename` param and it works to decode my file.

```python
    decompressed = so_compression.compression_wrapper(binary, binary_mode, compression, filename=os.path.basename(uri))
```

#### Versions
```
Windows-10-10.0.19045-SP0
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)]
smart_open 7.0.5
```

#### Checklist

Before you create the issue, please make sure you have:

- [X] Described the problem clearly
- [X] Provided a minimal reproducible example, including any required data
- [X] Provided the version numbers of the relevant software

### PR DESCRIPTION
**Pull request by ddelange**
#### Title

Please **pick a concise, informative and complete title** for your PR.
The title is important because it will appear in [our change log](https://github.com/RaRe-Technologies/smart_open/blob/master/CHANGELOG.md).

#### Motivation

Please explain the motivation behind this PR in the description.

If you're fixing a bug, link to the issue number like so:

Fix #841 

If you're adding a new feature, then consider opening a ticket and discussing it with the maintainers before you actually do the hard work.

#### Tests

If you're fixing a bug, consider [test-driven development](https://en.wikipedia.org/wiki/Test-driven_development):

1. Create a unit test that demonstrates the bug. The test should **fail**.
2. Implement your bug fix.
3. The test you created should now **pass**.

If you're implementing a new feature, include unit tests for it.

Make sure all existing unit tests pass.
You can run them locally using:

    pytest smart_open

If there are any failures, please fix them before creating the PR (or mark it as WIP, see below).

#### Work in progress

If you're still working on your PR, include "WIP" in the title.
We'll skip reviewing it for the time being.
Once you're ready to review, remove the "WIP" from the title, and ping one of the maintainers (e.g. mpenkov).

#### Checklist

Before you create the PR, please make sure you have:

- [x] Picked a concise, informative and complete title
- [x] Clearly explained the motivation behind the PR
- [x] Linked to any existing issues that your PR will be solving
- [x] Included tests for any new functionality
- [x] Checked that all unit tests pass

#### Workflow

Please avoid rebasing and force-pushing to the branch of the PR once a review is in progress.
Rebasing can make your commits look a bit cleaner, but it also makes life more difficult from the reviewer, because they are no longer able to distinguish between code that has already been reviewed, and unreviewed code.

### CODE REVIEW

**Comment by ddelange** [comment]
aha, [splittext will fail](https://github.com/piskvorky/smart_open/blob/v7.0.5/smart_open/compression.py#L149) to infer extension when the (http)URI has a query parameter appended to it, whereas the file_obj.name contains the relevant part of the URI only somehow.

**Comment by ddelange** [comment]
I think https://github.com/piskvorky/smart_open/pull/843 is a cleaner approach

**Review by mpenkov — APPROVED** [review]

**Comment by mpenkov** [comment]
Good work @ddelange ! Thank you.

**Comment by ddelange** [comment]
anything else from my side here?

**Comment by mpenkov** [comment]
No, thank you @ddelange !

**Pull request merged**
