### PR TITLE
Do not touch botocore unless it is installed

### PR DESCRIPTION
**Pull request by ddelange**
#### Title

Raise a proper S3 import exception (leftover from #785).

#### Motivation

Leftover from #785, not raising the proper Exception anymore:

```pytb
  File "/usr/share/python3/app/lib/python3.11/site-packages/smart_open/s3.py", line 121, in <module>
    RETRY = Retry()
            ^^^^^^^
  File "/usr/share/python3/app/lib/python3.11/site-packages/smart_open/s3.py", line 86, in __init__
    self.exceptions: List[Exception] = [botocore.exceptions.EndpointConnectionError]
                                        ^^^^^^^^
NameError: name 'botocore' is not defined
```

#### Checklist

Before you create the PR, please make sure you have:

- [x] Picked a concise, informative and complete title
- [x] Clearly explained the motivation behind the PR
- [x] Linked to any existing issues that your PR will be solving
- [x] Included tests for any new functionality
- [x] Checked that all unit tests pass

### CODE REVIEW

**Comment by ddelange** [comment]
cc @mpenkov

**Comment by ddelange** [comment]
hmm, now we're getting 
```pytb
smart_open/transport.py:22: in <module>
    _REGISTRY = {NO_SCHEME: smart_open.local_file}
E   AttributeError: partially initialized module 'smart_open' has no attribute 'local_file' (most likely due to a circular import)
```

What would be the proper fix?

**Comment by ddelange** [comment]
is there a point in time where we can test `import smart_open` before any optional deps are installed? to catch this case?

**Comment by mpenkov** [comment]
Fix #804

**Comment by mpenkov** [comment]
Thank you @ddelange !

**Comment by ddelange** [comment]
thanks too for the quick action!
[https://http.cat/202](https://http.cat/202)

**Pull request merged**
