### PR TITLE
Updates readline logic for azure to match s3

### PR DESCRIPTION
**Pull request by quantumfusion**
#### Title

Updates readline buffer management for azure, improving performance.

#### Motivation

Observed slow read times when iterating using `readlines()` from a 100MB csv file in Azure Blob Storage. Simple copies and reads were fine, slowness only observed with some code that was explicitly calling `readlines()`.

Borrows from the logic found in the S3 implementation, which was updated to be more efficient and does not perform as many scans on the local chunk of the remote file.

#### Tests

Confirmed clean run with `pytest -k test_azure`

#### Checklist

Before you create the PR, please make sure you have:

- [x] Picked a concise, informative and complete title
- [x] Clearly explained the motivation behind the PR
- [x] Linked to any existing issues that your PR will be solving
- [x] Included tests for any new functionality
- [x] Checked that all unit tests pass

#### Workflow

Please avoid rebasing and force-pushing to the branch of the PR once a review is in progress.
Rebasing can make your commits look a bit cleaner, but it also makes life more difficult from the reviewer, because they are no longer able to distinguish between code that has already been reviewed, and unreviewed code.

### CODE REVIEW

**Review by ddelange — APPROVED** [review]
LGTM

**Comment by ddelange** [comment]
@mpenkov can you review and merge?

**Comment by ddelange** [comment]
@quantumfusion can you add a `test_readlines` under this one based on it? https://github.com/piskvorky/smart_open/blob/a55794dee992dcebc3de23143c2c4a43ed3cc183/smart_open/tests/test_azure.py#L364

**Comment by quantumfusion** [comment]
> @quantumfusion can you add a `test_readlines` under this one based on it?
> 
> https://github.com/piskvorky/smart_open/blob/a55794dee992dcebc3de23143c2c4a43ed3cc183/smart_open/tests/test_azure.py#L364

@ddelange I added it briefly, but missed doing the linting which caught that `test_azure.py` already has a unittest for `test_readline`

**Comment by ddelange** [comment]
ah my bad! @mpenkov can you run CI?

**Comment by ddelange** [comment]
@mpenkov can you include this one in the next release?

**Comment by ddelange** [comment]
@mpenkov kind reminder:)

**Comment by mpenkov** [comment]
Thank you @quantumfusion and @ddelange .

Apologies for the delay, been a bit busy with real life recently :)

**Pull request merged**
