### PR TITLE
Added writing to webhdfs support

### PR DESCRIPTION
**Pull request by ziky90**
This PR adds ability to write directly to webhdfs.

**NOTE:**
Please do not merge yet

**TODO:**
 - tests
 - ~~investigation of `close`,` __enter__` and `__exit__` methods~~

### CODE REVIEW

**Comment by ziky90** [comment]
Implementation of writing to WebHDFS is basically done. I'll get back to tests probably at the end of the next week.

I have question regarding cached writing. System of writing to WebHDFS is quiet comparable to writing to S3, but caching is not necessary here. Should I add there some caching mechanism or should I let this on user?
Without caching, writing of one line == one http request.

**Comment by piskvorky** [comment]
I don't know of anyone else requesting WebHDFS, so your use case is the only one we have and care about for now. So... whatever works for you, I guess.

One HTTP request per line sounds pretty horrible... but if it works for you, it must cover at least one use case, so it cannot be completely useless. There's always room for improvement later.

**Comment by piskvorky** [comment]
@ziky90 Let me know when you're ready to merge -- I'll make a new release after that.

**Comment by ziky90** [comment]
I'd like to do caching for writing (one request per line does not fit our performance requirements) and some unit tests before merging. I'm just not sure if I'll be able to make it during this week.

**Comment by val314159** [comment]
it'd be nice to generalize this.  if you could do it by block, you could
actually mount this thing as a filesystem.

anyway, just thinking out loud :)

**Comment by ziky90** [comment]
@val314159 I think, that I don't fully understand your idea. Do you mean the `buffersize` parameter from here?

**Comment by val314159** [comment]
Well, my idea was only half-formed, I didn't even look at the underlying
source, but i'm just saying this could be the core of a mounted file
system.  But my experience is that network filesystem are mostly terrible
(unless you have a guaranteed fast network) unless you have a really good
caching layer.

(TL;DR caching is cool / block caches allow for filesystem mounts / don't
worry about it too much)

**Comment by ziky90** [comment]
I'm kind of stacked with writing test.
Unfortunately I have not found some any elegant solution for mocking the webhdfs (for reading there was simple workaround using just responses library, but it's getting more complicated for writing).

**Comment by piskvorky** [comment]
@ziky90 we'll release `smart_open` now (today/tmr). The "read WebHDFS support is in"; we can add this "write support" in the next release.

**Comment by ziky90** [comment]
I'm working on it right now and I'd like to finish it today.

**Comment by piskvorky** [comment]
OK, so we'll wait :)

**Comment by ziky90** [comment]
Some, at least minimal necessary tests were added, so from my point of view it is ready to merge, but additional tests for webhdfs (in general) are welcomed and might be also added later on.

**Comment by piskvorky** [comment]
All right. Tests pass, and I'm assuming this works for you, so let's merge.

Thanks @ziky90 !

**Pull request merged**
