### PR TITLE
README.rst: Code blocks

### PR DESCRIPTION
**Pull request by msabramo**
Will result in color syntax highlighting on PyPI.

### CODE REVIEW

**Comment by piskvorky** [comment]
Thanks!

Is this standard .rst, would it work with e.g. Sphinx / other tools?

**Comment by msabramo** [comment]
Yeah so docutils + Pygments supports it and will render it colored. 

GitHub will show it without color today but my PR has already been merged to make it work. They just need to deploy the change. 

I can't think of any downside.

**Comment by piskvorky** [comment]
I just [tested it](https://github.com/piskvorky/smart_open/tree/rst_test) and GitHub seems to support `.. code-block:: python` (not `pycon`).

Would `python` work on PyPI too?

**Comment by msabramo** [comment]
Yes. The `pycon` one is slightly better because it renders the `>>>` a little differently. However it doesn't work on GitHub yet, whereas the `python` one does. If you're impatient, you could use the `python` one and it will work pretty well on both PyPI and GitHub today.

https://github.com/atom/language-python/pull/48 is the PR I referenced before. I can't wait for Github to deploy it!

**Comment by msabramo** [comment]
I fixed the merge conflict and updated it to use `python`. It looks pretty good I think: https://github.com/msabramo/smart_open/tree/patch-2

**Comment by piskvorky** [comment]
Excellent, much thanks :)

**Comment by piskvorky** [comment]
Made a new release, the [PyPI page](https://pypi.python.org/pypi/smart_open) looks much better indeed, thanks again Marc!

**Comment by msabramo** [comment]
You're welcome! Glad to help!

**Pull request merged**
